WIP format to 4 spaces

diff --git a/.github/inactive/snyk-security.yml b/.github/inactive/snyk-security.yml
--- a/.github/inactive/snyk-security.yml
+++ b/.github/inactive/snyk-security.yml
@@ -20,77 +20,79 @@
 
 name: Snyk Security
 on:
-  pull_request:
-    branches: ['main']
+    pull_request:
+        branches: ['main']
 permissions:
-  contents: read
+    contents: read
 jobs:
-  snyk:
-    permissions:
-      contents: read # for actions/checkout to fetch code
-      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      # Set up Snyk CLI to check for security issues
-      - name: Set up Snyk CLI to check for security issues
-        # Snyk can be used to break the build when it detects security issues.
-        # In this case we want to upload the SAST issues to GitHub Code Scanning
-        uses: snyk/actions/setup@master
-        # For Snyk Open Source you must first set up the development environment for your application's dependencies
-        # For example for Node
-        #- uses: actions/setup-node@v3
-        #  with:
-        #    node-version: 16
-        env:
-          # This is where you will need to introduce the Snyk API token created with your Snyk account
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-          # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
-          # Use || true to not fail the pipeline
-      # setup node
-      - name: Install Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.5.0
-      # setup pnpm
-      - uses: pnpm/action-setup@v3
-        name: Install pnpm
-        with:
-          version: 8.14.0
-          run_install: false
-      # get cache
-      - name: Get pnpm store directory
-        shell: bash
-        run: |
-          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
-      - uses: actions/cache@v4
-        name: Setup pnpm cache
-        with:
-          path: ${{ env.STORE_PATH }}
-          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-store-
-      # install dependencies
-      - name: Install dependencies
-        run: pnpm install --frozen-lockfile
-      - name: Snyk Code test
-        run: snyk code test --sarif > snyk-code.sarif # || true
-        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
-      - name: Snyk Open Source monitor
-        run: snyk monitor --all-projects
-        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
-        # Use || true to not fail the pipeline.
-      - name: Snyk IaC test and report
-        run: snyk iac test --report # || true
-        # Build the docker image for testing
-      - name: Build a Docker image
-        run: docker build -t your/image-to-test .
-        # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
-      - name: Snyk Container monitor
-        run: snyk container monitor your/image-to-test --file=Dockerfile
-        # Push the Snyk Code results into GitHub Code Scanning tab
-      - name: Upload result to GitHub Code Scanning
-        uses: github/codeql-action/upload-sarif@v2
-        with:
-          sarif_file: snyk-code.sarif
+    snyk:
+        permissions:
+            contents: read # for actions/checkout to fetch code
+            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
+            # Set up Snyk CLI to check for security issues
+            - name: Set up Snyk CLI to check for security issues
+              # Snyk can be used to break the build when it detects security issues.
+              # In this case we want to upload the SAST issues to GitHub Code Scanning
+              uses: snyk/actions/setup@master
+              # For Snyk Open Source you must first set up the development environment for your application's dependencies
+              # For example for Node
+              #- uses: actions/setup-node@v3
+              #  with:
+              #    node-version: 16
+              env:
+                  # This is where you will need to introduce the Snyk API token created with your Snyk account
+                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+                  # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
+                  # Use || true to not fail the pipeline
+            # setup node
+            - name: Install Node.js
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 20.5.0
+            # setup pnpm
+            - uses: pnpm/action-setup@v3
+              name: Install pnpm
+              with:
+                  version: 8.14.0
+                  run_install: false
+            # get cache
+            - name: Get pnpm store directory
+              shell: bash
+              run: |
+                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
+            - uses: actions/cache@v4
+              name: Setup pnpm cache
+              with:
+                  path: ${{ env.STORE_PATH }}
+                  key:
+                      ${{ runner.os }}-pnpm-store-${{
+                      hashFiles('**/pnpm-lock.yaml') }}
+                  restore-keys: |
+                      ${{ runner.os }}-pnpm-store-
+            # install dependencies
+            - name: Install dependencies
+              run: pnpm install --frozen-lockfile
+            - name: Snyk Code test
+              run: snyk code test --sarif > snyk-code.sarif # || true
+              # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
+            - name: Snyk Open Source monitor
+              run: snyk monitor --all-projects
+              # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
+              # Use || true to not fail the pipeline.
+            - name: Snyk IaC test and report
+              run: snyk iac test --report # || true
+              # Build the docker image for testing
+            - name: Build a Docker image
+              run: docker build -t your/image-to-test .
+              # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
+            - name: Snyk Container monitor
+              run: snyk container monitor your/image-to-test --file=Dockerfile
+              # Push the Snyk Code results into GitHub Code Scanning tab
+            - name: Upload result to GitHub Code Scanning
+              uses: github/codeql-action/upload-sarif@v2
+              with:
+                  sarif_file: snyk-code.sarif
